from scievo.core.code_env import LocalEnv
from scievo.core.plan import PlanState
from scievo.core.types import HistoryState, RBankState, ToolsetState


class DataAgentState(ToolsetState, PlanState, HistoryState, RBankState):
    """State of an agent"""

    user_query: str
    # Local environment for the agent
    workspace: LocalEnv

    # Optional additional description of the data (input)
    data_desc: str | None = None

    # talking mode
    talk_mode: bool = False

    # output summary generated by the agent (output)
    output_summary: str | None = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.toolsets.append("fs")
