from pydantic import BaseModel, Field


class Plan(BaseModel):
    """Plan to follow in future. Generated by LLM and used in `response_format` of LLM APIs."""

    steps: list[str] = Field(description="different steps to follow, should be in sorted order")


class PlanState(BaseModel):
    """Plan to follow in future. Used in agent state."""

    # current plan
    plans: Plan | None = None
    # remaining plans to execute
    remaining_plans: list[str] = []
    # past plans that have been executed
    past_plans: list[str] = []
