from loguru import logger

from scider.core import constant
from scider.core.llms import ModelRegistry
from scider.core.plan import Plan
from scider.core.types import Message
from scider.core.utils import parse_json_from_llm_response
from scider.prompts import PROMPTS

from .state import DataAgentState

LLM_NAME = "plan"
AGENT_NAME = "data_planner"


@logger.catch
def planner_node(agent_state: DataAgentState) -> DataAgentState:
    logger.trace("planner_node of Agent {}", AGENT_NAME)

    user_query_msg = Message(
        role="user",
        content=agent_state.user_query,
        agent_sender=AGENT_NAME,
    )

    agent_state.add_message(user_query_msg)

    msg = ModelRegistry.completion(
        LLM_NAME,
        agent_state.patched_history,
        system_prompt=(
            Message(
                role="system",
                content=PROMPTS.data.planner_system_prompt.render(is_replanner=False),
            )
            .with_log(cond=constant.LOG_SYSTEM_PROMPT)
            .content
        ),
        agent_sender=AGENT_NAME,
    ).with_log()

    agent_state.add_message(msg)

    # NOTE: we don't add the message to the history
    plans = parse_json_from_llm_response(msg, Plan)

    # NOTE:
    agent_state.add_message(
        Message(
            role="user",
            content="Follow the current plan.",
            agent_sender=AGENT_NAME,
        )
    )

    agent_state.plans = plans
    agent_state.remaining_plans = plans.steps
    agent_state.past_plans = []

    # dummy user response, just for logging
    if len(agent_state.remaining_plans) > 0:
        Message(
            role="user",
            content=PROMPTS.data.replanner_user_response.render(
                next_step=agent_state.remaining_plans[0],
            ),
            agent_sender=AGENT_NAME,
        ).with_log()
    else:
        logger.warning("No plans generated by planner - remaining_plans is empty")

    planner_output = msg.content if "msg" in locals() and msg.content else "No planner output"

    agent_state.intermediate_state.append(
        {
            "node_name": "planner",
            "output": planner_output,
        }
    )

    return agent_state


def advance_plan_node(agent_state: DataAgentState) -> DataAgentState:
    """Advance to the next plan step, or set talk_mode if all steps are done.

    This replaces the LLM-based replanner with a simple state machine:
    pop current step → if more steps remain, inject next step prompt → else talk_mode.
    """
    logger.trace("advance_plan_node of Agent {}", AGENT_NAME)

    if len(agent_state.remaining_plans) == 0:
        logger.debug("All plans are done, going into talk mode")
        agent_state.talk_mode = True
        return agent_state

    # Move current step to past_plans
    agent_state.past_plans.append(agent_state.remaining_plans.pop(0))

    if len(agent_state.remaining_plans) > 0:
        next_step = agent_state.remaining_plans[0]
        agent_state.add_message(
            Message(
                role="user",
                content=PROMPTS.data.replanner_user_response.render(
                    next_step=next_step,
                ),
                agent_sender=AGENT_NAME,
            )
        )
        logger.debug(
            "Advanced plan: {}/{} steps done, next: {}",
            len(agent_state.past_plans),
            len(agent_state.past_plans) + len(agent_state.remaining_plans),
            next_step[:80],
        )
    else:
        logger.debug("All plan steps completed ({} total)", len(agent_state.past_plans))
        agent_state.talk_mode = True

    agent_state.intermediate_state.append(
        {
            "node_name": "advance_plan",
            "output": (
                f"Steps done: {len(agent_state.past_plans)}, "
                f"Remaining: {len(agent_state.remaining_plans)}, "
                f"Talk mode: {agent_state.talk_mode}"
            ),
        }
    )

    return agent_state


def should_advance(agent_state: DataAgentState) -> str:
    """Route after advance_plan: back to gateway if more steps, else approve_final."""
    if agent_state.talk_mode:
        return "approve_final"
    else:
        return "gateway"
