from typing import Literal

from scider.core.code_env import LocalEnv
from scider.core.types import HistoryState, RBankState, ToolsetState


class DataAgentState(ToolsetState, HistoryState, RBankState):
    """State of the data analysis agent.

    Two-phase flow:
    1. analysis: Initial data analysis using tools
    2. deep_analysis: Re-analysis with paper/dataset context
    """

    user_query: str
    workspace: LocalEnv

    # Optional additional description of the data (input)
    data_desc: str | None = None

    # Current analysis phase
    phase: Literal["analysis", "deep_analysis"] = "analysis"

    # Set True when gateway loop should exit (assistant responded without tool calls)
    talk_mode: bool = False

    # Output summary generated by the agent
    output_summary: str | None = None

    # Paper subagent results
    papers: list[dict] = []
    datasets: list[dict] = []
    metrics: list[dict] = []
    paper_search_summary: str | None = None

    # Intermediate states
    intermediate_state: list[dict] = []

    # Approval status (transient, for conditional edge routing)
    approval_status: str | None = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.toolsets.append("fs")
